version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          name: Restore Dependency Cache
          key: node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: |
            if [ -d node_modules ]; then
              echo "Restored node_modules from cache."
            else
              npm ci
            fi
      - save_cache:
          name: Save Dependency Cache
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Lint JavaScript
          command: npm run eslint
      - run:
          name: Lint Styles
          command: npm run stylelint
      - run:
          name: Build Docker Image
          command: docker build . -t "dylantreisman.com:$CIRCLE_SHA1"
