version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:carbon
commands:
  restore_node_modules:
    description: "Restore node_modules from cache"
    steps:
      - restore_cache:
          name: Restore Dependency Cache
          key: node_modules-{{ checksum "package-lock.json" }}
  restore_docker_image:
    description: "Restore docker image from workspace"
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Load Docker Image
          command: docker load < dylantreisman.com.tar
jobs:
  node_modules:
    executor: node
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: Install Dependencies
          command: |
            if [ -d node_modules ]; then
              echo "Restored node_modules from cache."
            else
              npm ci
            fi
      - save_cache:
          name: Save Dependency Cache
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  lint_js:
    executor: node
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: Lint JavaScript
          command: npm run eslint
  lint_styles:
    executor: node
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: Lint Styles
          command: npm run stylelint
  build_docker:
    executor: node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build . -t "dylantreisman.com:$CIRCLE_SHA1"
      - run:
          name: Save Docker Image
          command: docker save "dylantreisman.com:$CIRCLE_SHA1" > dylantreisman.com.tar
      - store_artifacts:
          path: dylantreisman.com.tar
      - persist_to_workspace:
          root: .
          paths:
            - dylantreisman.com.tar
  test_docker:
    executor: node
    steps:
      - checkout
      - restore_docker_image
      - run:
          name: Test Docker Image
          command: |
            docker run -d -p 5000:5000 "dylantreisman.com:$CIRCLE_SHA1"
            ssh remote-docker "curl --retry 5 --retry-delay 5 -v localhost:5000 | grep '<title>Dylan Treisman</title>'"
  npm_audit:
    executor: node
    steps:
      - checkout
      - run:
          name: Audit Dependency Vulnerabilities
          command: npm audit --audit-level=low --json
  npm_outdated:
    executor: node
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: Check Outdated Dependencies
          command: |
            set +o pipefail
            npm outdated --json | jq -e '., length <= 3'
workflows:
  version: 2.1
  commit:
    jobs:
      - node_modules
      - lint_js:
          requires:
            - node_modules
      - lint_styles:
          requires:
            - node_modules
      - build_docker
      - test_docker:
          requires:
            - build_docker
  daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - npm_audit
      - npm_outdated
