version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.0.0
executors:
  node:
    docker:
      - image: cimg/node:lts
commands:
  restore_node_modules:
    description: "Restore node_modules from cache"
    steps:
      - restore_cache:
          name: Restore Dependency Cache
          key: node_modules-{{ checksum "package-lock.json" }}
  restore_docker_image:
    description: "Restore docker image from workspace"
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Load Docker Image
          command: docker load < dylantreisman.com.tar
  execute_and_store_tests:
    description: "Run a test and store the results"
    parameters:
      test_name:
        type: string
        default: "Test"
      test_command:
        type: string
        default: "test"
    steps:
      - run:
          name: << parameters.test_name >>
          command: mkdir -p reports/<< parameters.test_command >>/ && npm run -s << parameters.test_command >>:junit > reports/<< parameters.test_command >>/results.xml
      - store_test_results:
          path: reports
jobs:
  node_modules:
    executor: node
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: Install Dependencies
          command: |
            if [ -d node_modules ]; then
              echo "Restored node_modules from cache."
            else
              npm ci
            fi
      - save_cache:
          name: Save Dependency Cache
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  lint_js:
    executor: node
    steps:
      - checkout
      - restore_node_modules
      - execute_and_store_tests:
          test_name: Lint JavaScript
          test_command: eslint
  lint_styles:
    executor: node
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: Lint Styles
          command: npm run stylelint
  lint_dockerfile:
    docker:
      - image: hadolint/hadolint
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile
  build_docker:
    executor: node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build . -t "dylantreisman.com:$CIRCLE_SHA1"
      - run:
          name: Save Docker Image
          command: docker save "dylantreisman.com:$CIRCLE_SHA1" > dylantreisman.com.tar
      - store_artifacts:
          path: dylantreisman.com.tar
      - persist_to_workspace:
          root: .
          paths:
            - dylantreisman.com.tar
  test_docker:
    executor: node
    steps:
      - checkout
      - restore_docker_image
      - run:
          name: Test Docker Image
          command: |
            docker run -d -p 5000:5000 "dylantreisman.com:$CIRCLE_SHA1"
            ssh remote-docker "curl --retry 5 --retry-delay 5 -v localhost:5000 | grep '<title>Dylan Treisman</title>'"
  push_docker:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - restore_docker_image
      - run:
          name: Push Docker Image to ECR
          command: |
            aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin $ECR_REGISTRY
            docker tag "dylantreisman.com:$CIRCLE_SHA1" "$ECR_REGISTRY:$CIRCLE_SHA1"
            docker tag "dylantreisman.com:$CIRCLE_SHA1" "$ECR_REGISTRY:latest"
            docker push "$ECR_REGISTRY"
  npm_audit:
    executor: node
    steps:
      - checkout
      - run:
          name: Audit Dependency Vulnerabilities
          command: npm audit --audit-level=low --json
  npm_outdated:
    executor: node
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: Check Outdated Dependencies
          command: |
            set +o pipefail
            npm outdated --json | jq -e '., length <= 3'
workflows:
  version: 2.1
  commit:
    jobs:
      - node_modules
      - lint_js:
          requires:
            - node_modules
      - lint_styles:
          requires:
            - node_modules
      - build_docker
      - test_docker:
          requires:
            - build_docker
      - lint_dockerfile
      - push_docker:
          filters:
            branches:
              only: master
          requires:
            - lint_js
            - lint_styles
            - lint_dockerfile
            - test_docker
  daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - npm_audit
      - npm_outdated
