version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: docker build . -t "dylantreisman.com:$CIRCLE_SHA1"
