version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          name: Save Dependency Cache
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Build Docker Image
          command: docker build . -t "dylantreisman.com:$CIRCLE_SHA1"
