// Temporary
import React from "react";
import PropTypes from "prop-types";

const Lipsum = (props) => (
    <div className={props.className}>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque et commodo sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus auctor nisi vitae rutrum feugiat. Aenean tempus dui est, nec dapibus diam ornare id. Aenean urna ipsum, auctor quis cursus sit amet, gravida eget ex. In aliquam, odio sit amet sollicitudin fringilla, ante libero accumsan neque, iaculis volutpat est tortor aliquam mauris. Praesent a posuere magna. In fringilla dignissim quam, eget gravida mauris lobortis ac. Praesent posuere tempor massa sed elementum. Nunc lobortis aliquam diam, pharetra auctor arcu vehicula ut. Donec non elementum orci. Vestibulum eget ligula vitae leo fermentum sagittis a ac arcu.
        <br/>Praesent imperdiet nec elit at dignissim. Nullam libero mauris, blandit ut felis sed, dignissim condimentum ante. Praesent id lorem rutrum, mollis elit quis, varius est. Vivamus lacinia lacinia condimentum. Sed tristique justo ex, in tempor est pretium quis. Fusce malesuada sem elit, vel blandit nisl luctus id. Donec massa arcu, pretium eu accumsan quis, commodo id augue. Suspendisse fermentum nisl nec orci volutpat, eget blandit nibh pellentesque. Vivamus felis ligula, commodo id lobortis vitae, blandit non mauris. Maecenas eu nisi tristique, euismod purus sit amet, semper velit. Aliquam eros felis, pretium non massa id, pellentesque laoreet purus. Proin venenatis vulputate lorem eu tristique. Donec finibus lectus elit, non accumsan lorem ultricies eget. Phasellus at dignissim tellus, eget gravida nunc.
        <br/>Praesent imperdiet nec elit at dignissim. Nullam libero mauris, blandit ut felis sed, dignissim condimentum ante. Praesent id lorem rutrum, mollis elit quis, varius est. Vivamus lacinia lacinia condimentum. Sed tristique justo ex, in tempor est pretium quis. Fusce malesuada sem elit, vel blandit nisl luctus id. Donec massa arcu, pretium eu accumsan quis, commodo id augue. Suspendisse fermentum nisl nec orci volutpat, eget blandit nibh pellentesque. Vivamus felis ligula, commodo id lobortis vitae, blandit non mauris. Maecenas eu nisi tristique, euismod purus sit amet, semper velit. Aliquam eros felis, pretium non massa id, pellentesque laoreet purus. Proin venenatis vulputate lorem eu tristique. Donec finibus lectus elit, non accumsan lorem ultricies eget. Phasellus at dignissim tellus, eget gravida nunc.
        <br/>Aliquam blandit imperdiet neque, at tristique eros congue eget. Etiam dictum nisi lacus, vel maximus dui congue eget. Curabitur erat tellus, euismod eu mi a, lobortis sodales ipsum. Maecenas sit amet est sed risus bibendum aliquam sit amet vel quam. In nibh justo, sodales at odio eu, convallis egestas lacus. Sed at convallis purus, vitae maximus augue. Quisque eget blandit purus, eu venenatis erat. Donec congue pharetra justo et aliquet. Pellentesque commodo sit amet leo non maximus. Cras ultrices lectus cursus justo interdum vestibulum. Nunc in leo cursus, molestie tellus eget, suscipit nunc. Praesent sagittis quam id accumsan dapibus. Donec posuere dolor nunc, eu suscipit urna accumsan eget. Cras consequat neque ac augue semper, at ornare ex viverra. Sed tempor libero ut sapien volutpat, nec convallis nisl accumsan.
        <br/>Aliquam blandit imperdiet neque, at tristique eros congue eget. Etiam dictum nisi lacus, vel maximus dui congue eget. Curabitur erat tellus, euismod eu mi a, lobortis sodales ipsum. Maecenas sit amet est sed risus bibendum aliquam sit amet vel quam. In nibh justo, sodales at odio eu, convallis egestas lacus. Sed at convallis purus, vitae maximus augue. Quisque eget blandit purus, eu venenatis erat. Donec congue pharetra justo et aliquet. Pellentesque commodo sit amet leo non maximus. Cras ultrices lectus cursus justo interdum vestibulum. Nunc in leo cursus, molestie tellus eget, suscipit nunc. Praesent sagittis quam id accumsan dapibus. Donec posuere dolor nunc, eu suscipit urna accumsan eget. Cras consequat neque ac augue semper, at ornare ex viverra. Sed tempor libero ut sapien volutpat, nec convallis nisl accumsan.
        <br/>Donec eu lorem ante. Curabitur eleifend neque lacus, pretium fermentum justo mattis sit amet. Duis ut nibh aliquet, placerat lorem a, volutpat sem. Aliquam ex mauris, consectetur sit amet purus maximus, fringilla porta tortor. Vivamus nec lacus justo. Suspendisse porta aliquet diam vel lobortis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada massa nec sapien varius, nec condimentum dolor aliquam. Quisque ornare tortor suscipit eleifend fringilla. In nec leo risus.
        <br/>Donec eu lorem ante. Curabitur eleifend neque lacus, pretium fermentum justo mattis sit amet. Duis ut nibh aliquet, placerat lorem a, volutpat sem. Aliquam ex mauris, consectetur sit amet purus maximus, fringilla porta tortor. Vivamus nec lacus justo. Suspendisse porta aliquet diam vel lobortis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada massa nec sapien varius, nec condimentum dolor aliquam. Quisque ornare tortor suscipit eleifend fringilla. In nec leo risus.
        <br/>Quisque venenatis quis magna ac volutpat. Duis iaculis augue vehicula ante efficitur, at efficitur nisi feugiat. Nulla mauris tellus, gravida gravida velit sit amet, facilisis facilisis magna. Donec ac dolor eros. Nullam mollis dui id erat faucibus ornare. Vestibulum porta neque quis tincidunt placerat. Cras in lacus quis ligula blandit varius ut quis diam. Aenean lorem odio, tempus eu nulla eget, sodales sollicitudin turpis. In a mi vel diam tempor placerat non id ipsum. Vivamus sagittis ultrices pulvinar. Phasellus egestas, arcu in imperdiet bibendum, libero orci fermentum odio, eu tempus enim elit ac diam.
        <br/>Quisque venenatis quis magna ac volutpat. Duis iaculis augue vehicula ante efficitur, at efficitur nisi feugiat. Nulla mauris tellus, gravida gravida velit sit amet, facilisis facilisis magna. Donec ac dolor eros. Nullam mollis dui id erat faucibus ornare. Vestibulum porta neque quis tincidunt placerat. Cras in lacus quis ligula blandit varius ut quis diam. Aenean lorem odio, tempus eu nulla eget, sodales sollicitudin turpis. In a mi vel diam tempor placerat non id ipsum. Vivamus sagittis ultrices pulvinar. Phasellus egestas, arcu in imperdiet bibendum, libero orci fermentum odio, eu tempus enim elit ac diam.
    </div>
);
Lipsum.propTypes = {
    className: PropTypes.string.isRequired,
};
export default Lipsum;
